[package]
authors = ['Setheum Labs<https://github.com/Setheum-Labs>']
description = 'sett currencies SettCurrencies pallet'
edition = '2018'
homepage = 'https://setheum.xyz'
license = 'Apache-2.0 License'
name = "stp258"
repository = 'https://github.com/Setheum-Labs/Setheum/'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies]
adapters = { default-features = false, package = 'storage-adapters', version = '0.0.3', path = '../../storage-adapters' }
fetch-price = { default-features = false, package = 'fetch-price', version = '0.1.0', path = '../fetch-price' }
sp-std = { default-features = false, optional = true, version = '2.0.0' }


serde = { version = "1.0.118", optional = true }
frame-support = { default-features = false, version = '2.0.0' }
frame-system = { default-features = false, version = '2.0.0' }

orml-traits = { default-features = false, version = '0.3.2' }
orml-utilities = { default-features = false, version = '0.3.2' }

num-rational = { default-features = false, version = '0.3.2' }

fixed = { default-features = false, version = '1.5.0' }

sp-runtime = { default-features = false, optional = true, version = '2.0.0' }

[dev-dependencies]
sp-core = { default-features = false, version = '2.0.0' }
sp-io = { default-features = false, version = '2.0.0' }
orml-tokens = { default-features = false, version = '0.3.2' }

pallet-assets = "2.0.0"
pallet-balances = "2.0.0"
clear_on_drop = { version = "0.2.4", features = ["no_cc"] }	# https://github.com/paritytech/substrate/issues/4179

[features]
default = ['std']
std = [
    "adapters/std",
    'codec/std',
    "fetch-price/std",
    "fixed/std",
    'frame-support/std',
    'frame-system/std',
    "num-rational/std",
	"orml-traits/std",
    "orml-tokens/std",
    'orml-utilities/std',
	"serde/std",
    "sp-runtime/std",
    "sp-std",
]
