[package]
authors = ['Setheum Labs<https://github.com/Setheum-Labs>']
description = 'price pallet template'
edition = '2018'
homepage = 'https://setheum.xyz'
license = 'Apache-2.0 License'
name = 'price'
repository = 'https://github.com/Setheum-Labs/Setheum/'
version = '0.1.0'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = [ "derive"] }
safe-mix = { default-features = false, version = '1.0.0' }
# substrate deps
frame-support = { default-features = false, version = "2.0.0" }
frame-system = { default-features = false, version = "2.0.0" }
# pallets
fetch-price = { default-features = false, package = "fetch-price", version = "0.1.0", path = "../fetch-price" }
stp258 = { default-features = false, package = "stp258", version = "0.1.0", path = "../stp258" }

[dev-dependencies]
sp-core = { default-features = false, version = "2.0.0-alpha.5" }
sp-io = { default-features = false, version = "2.0.0-alpha.5" }
sp-runtime = { default-features = false, version = "2.0.0-alpha.5" }

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'safe-mix/std',
    'frame-system/std',
    'fetch-price/std',
    'stp258/std',
]