[package]
authors = ['Setheum Labs<https://github.com/Setheum-Labs>']
description = 'fetch-price pallet template'
edition = '2018'
homepage = 'https://setheum.xyz'
license = 'Apache-2.0 License'
name = "fetch-price"
repository = 'https://github.com/Setheum-Labs/Setheum/'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.5", default-features = false }
frame-support = { version = "2.0.0", default-features = false}
frame-system = { version = "2.0.0", default-features = false }
serde = { version = "1.0.118", optional = true }
sp-core = { version = "2.0.0", default-features = false }
sc-keystore = { version = "2.0.0", optional = true }
sp-io = { version = "2.0.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }
lite-json = { version = "0.1", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"serde",
	"lite-json/std",
	"sp-core/std",
	"sp-io/std",
	"sc-keystore",
	"sp-runtime/std",
	"sp-std/std",
]